<?php
// The rendering file is made in the form of an associated array, the values ​​of this array are written to the $ texts array over the old ones.
$labels['lbl1'] = 'Remove Duplicate Emails'; // Localized label on the button.
$labels['lbl2'] = 'Remove or mark duplicate emails'; // Localized button tooltip. // $labels['lbl14'] = 'Plugin searches and marks duplicate emails. <br /> ';
// Pop-up window.
$labels['lbl3'] = 'Setting parameters'; // Title of the dialog box.
$labels['lbl4'] = 'Select Settings'; // Title of the dialog box content.
// Window buttons.
$labels['lbl5'] = 'Run';
$labels['lbl6'] = 'Remove Settings';
// First frame.
$labels['lbl7'] = 'Number of messages to process';
$labels['lbl8'] = 'All messages';
$labels['lbl9'] = 'Process all messages from the list';
$labels['lbl10'] = 'Selected';
$labels['lbl11'] = 'Only processes the highlighted messages in the current list';
$labels['lbl12'] = 'Close this window and highlight messages for processing';
// Second frame.
$labels['lbl13'] = 'Mode of processing found duplicate letters';
$labels['lbl14'] = 'Label';
$labels['lbl15'] = 'Plugin searches and marks duplicate emails. <br /> Sets two flags: "DUBLIKAT" and "DELETED" ';
$labels['lbl16'] = 'Delete';
$labels['lbl17'] = 'Plugin removes duplicate emails.';
// Third frame.
$labels['lbl18'] = 'Plugin Mode'; // Plugin searches for and marks duplicate emails. <br /> <br /> '.'Sets two flags: "DUBLIKAT" and "DELETED"';
$labels['lbl19'] = 'Via Browser';
$labels['lbl20'] = 'Plugin Sends Requests From Browser';
$labels['lbl21'] = 'Server Edition';
$labels['lbl22'] = '(in development)';
// Warning window.
$labels['lbl23'] = 'Unable to get the "uid" of the message.';
$labels['lbl24'] = 'Reload this page.';
// Messages to the client environment.
$labels['lbl25'] = 'Save settings ...';
$labels['lbl26'] = 'Settings saved. Start searching for duplicates. ';
$labels['lbl27'] = 'Removing settings ...';
$labels['lbl28'] = 'Settings removed.';
$labels['lbl29'] = 'Looking for duplicates ...';
$labels['lbl30'] = 'Continue looking for duplicates ...';
$labels['successful'] = 'Checking completed.';
